services:
#    audio.example:
#        class: Audio\AudioBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.upload_file:
        class: Audio\AudioBundle\Services\FileUploader
        arguments: ['%upload_directory%']